package audit

import (
	"bytes"
	"context"
	"crypto/tls"
	"encoding/json"
	"fmt"
	"io"
	"net"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/app-sre/gabi/pkg/env/splunk"
	"github.com/app-sre/gabi/pkg/version"
)

const (
	splunkSource     = "gabi"
	splunkSourceType = "json"

	connectTimeout = 5 * time.Second
	requestTimeout = 30 * time.Second
)

type SplunkAudit struct {
	SplunkEnv *splunk.Env

	client *http.Client
}

var _ Audit = (*SplunkAudit)(nil)

// SplunkResponseError describes an HTTP response from Splunk without retaining
// its body. Error responses from proxies and WAFs can contain sensitive or
// misleading HTML, so callers can log this error safely.
type SplunkResponseError struct {
	StatusCode     int
	EndpointOrigin string
	MediaType      string
	Reason         string
	Err            error
}

func (e *SplunkResponseError) Error() string {
	message := fmt.Sprintf(
		"Splunk audit failed: received HTTP %d from %s (expected JSON, got %s): %s",
		e.StatusCode,
		e.EndpointOrigin,
		e.MediaType,
		e.Reason,
	)
	if e.Err != nil {
		return fmt.Sprintf("%s: %v", message, e.Err)
	}
	return message
}

func (e *SplunkResponseError) Unwrap() error { return e.Err }

type SplunkEventData struct {
	Query     string `json:"query"`
	User      string `json:"user"`
	Namespace string `json:"namespace"`
	Pod       string `json:"pod"`
}

type SplunkQueryData struct {
	Event      *SplunkEventData `json:"event"`
	Index      string           `json:"index"`
	Host       string           `json:"host"`
	Source     string           `json:"source"`
	SourceType string           `json:"sourcetype"`
	Time       int64            `json:"time"`
}

type Option func(*SplunkAudit)

func WithHTTPClient(client *http.Client) Option {
	return func(s *SplunkAudit) {
		s.SetHTTPClient(client)
	}
}

func NewSplunkAudit(splunk *splunk.Env, options ...Option) *SplunkAudit {
	s := &SplunkAudit{SplunkEnv: splunk}

	s.client = &http.Client{
		Transport: &http.Transport{
			DialContext: (&net.Dialer{
				Timeout: connectTimeout,
			}).DialContext,
			TLSClientConfig: &tls.Config{
				InsecureSkipVerify: true,
			},
		},
	}

	for _, option := range options {
		option(s)
	}

	return s
}

func (d *SplunkAudit) SetHTTPClient(client *http.Client) {
	d.client = client
}

func (d *SplunkAudit) Write(ctx context.Context, q *QueryData) error {
	query := &SplunkQueryData{
		Index:      d.SplunkEnv.Index,
		Host:       d.SplunkEnv.Host,
		Source:     splunkSource,
		SourceType: splunkSourceType,
		Time:       q.Timestamp,
	}

	query.Event = &SplunkEventData{
		Query:     q.Query,
		User:      q.User,
		Namespace: d.SplunkEnv.Namespace,
		Pod:       d.SplunkEnv.Pod,
	}

	content, err := json.Marshal(query)
	if err != nil {
		return fmt.Errorf("unable to marshal Splunk audit: %w", err)
	}

	endpoint := fmt.Sprintf("%s/services/collector/event", d.SplunkEnv.Endpoint)

	ctx, cancel := context.WithTimeout(ctx, requestTimeout)
	defer cancel()

	req, err := http.NewRequestWithContext(ctx, http.MethodPost, endpoint, bytes.NewBuffer(content))
	if err != nil {
		return fmt.Errorf("unable to create request to Splunk: %w", err)
	}
	req.Header.Set("Accept", "application/json")
	req.Header.Set("Authorization", fmt.Sprintf("Splunk %s", d.SplunkEnv.Token))
	req.Header.Set("Content-Type", "application/json; charset=utf-8")
	req.Header.Set("User-Agent", fmt.Sprintf("GABI/%s", version.Version()))

	resp, err := d.client.Do(req)
	if err != nil {
		return fmt.Errorf("unable to send request to Splunk: %w", err)
	}
	defer func() { _ = resp.Body.Close() }()
	mediaType := responseMediaType(resp.Header.Get("Content-Type"))
	origin := endpointOrigin(req.URL)

	// A successful-looking JSON body must not override an HTTP error status.
	// In particular, WAF responses may be HTML or JSON generated by an
	// intermediary rather than by Splunk HEC.
	if resp.StatusCode < http.StatusOK || resp.StatusCode >= http.StatusMultipleChoices {
		return &SplunkResponseError{
			StatusCode:     resp.StatusCode,
			EndpointOrigin: origin,
			MediaType:      mediaType,
			Reason:         "unexpected HTTP status",
		}
	}

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return fmt.Errorf("unable to read Splunk response body: %w", err)
	}

	splunk := struct {
		Code int    `json:"code"`
		Text string `json:"text"`
	}{}

	err = json.Unmarshal(body, &splunk)
	if err != nil {
		return &SplunkResponseError{
			StatusCode:     resp.StatusCode,
			EndpointOrigin: origin,
			MediaType:      mediaType,
			Reason:         "invalid JSON response",
			Err:            err,
		}
	}
	if splunk.Code > 0 {
		return &SplunkResponseError{
			StatusCode:     resp.StatusCode,
			EndpointOrigin: origin,
			MediaType:      mediaType,
			Reason:         fmt.Sprintf("HEC response code %d", splunk.Code),
		}
	}

	return nil
}

func endpointOrigin(endpoint *url.URL) string {
	return fmt.Sprintf("%s://%s", endpoint.Scheme, endpoint.Host)
}

func responseMediaType(contentType string) string {
	mediaType := strings.TrimSpace(strings.Split(contentType, ";")[0])
	if mediaType == "" {
		return "unknown"
	}
	return mediaType
}
