apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/app-sre/gabi?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch
      == "main"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: gabi-main
    appstudio.openshift.io/component: gabi-integration-main
    pipelines.appstudio.openshift.io/type: build
  name: gabi-integration-main-on-push
  namespace: app-sre-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/app-sre-tenant/gabi-main/gabi-integration-main:{{revision}}
  - name: dockerfile
    value: Dockerfile.integration
  - name: path-context
    value: .
  - name: ephemeral-namespace-run-script
    value: test/ephemeral-integration-test.sh
  pipelineRef:
    params:
    - name: url
      value: https://github.com/app-sre/shared-pipelines
    - name: revision
      value: main
    - name: pathInRepo
      value: pipelines/multi-arch-build-pipeline.yaml
    resolver: git
  taskRunTemplate:
    serviceAccountName: build-pipeline-gabi-integration-main
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      status: {}
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
